### PR TITLE
keyboard_creator.sh: Script improvements

### PR DESCRIPTION
**Pull request by Razerban**
Please find listed below the non-breaking changes and improvements introduced in this PR:
- Replaced legacy backticks \`...\` with the $(...) notation.
- Made the use of the `test` operator consistent across the script.
- Separated the argument parsing code from the values check code.
- Fixed the issue with the `sed` commands by making them compatible with macOS.
- Added a verbose logging option to make debugging easier.
- Defined the commands to be used to avoid using aliases if configured.
- Made constant values readonly.
- Merged the `kicad_setup` and the `check` functions as it made more sense to have them together.
- Updated the return  and exit codes to help identify the issues when they occur.
- Added local variables inside the functions to help with the code clarity.
- Changed the flag values from `true` and `false` to `1` and `0` respectively as it's easier to use numbers in comparisons.
- Rearranged the code so that the global variables and constants definitions go to the top.
- Printing to stdout and to stderr depending on nature of message to be displayed.

The script has been tested on macOS Monterey 12.1 and Debian Bullseye.

### CODE REVIEW

**Comment by Gondolindrim** [comment]
Nice! That is some fancy stuff right here!

So I am getting this error when I run `./keyboard_creator.sh -p test -s MX_soldermask` :

image

And when I go to the KiCAD footprint and symbol librarires tables, `fp-lib-table` and `sym-lib-table` respectively, the libraries were not added at all!

image

image

So when I remove the two ticks from the `sed` command it works perfectly here (I'm running Arch) . Can you please check if this works on your systems?

**Comment by Gondolindrim** [comment]
There is also an issue with the usage function (`-h` option):

image

For some reason the linebreaks are not being processed in `echo2stderr` . I tried adding the `-e` option to the function's definition but to no avail; simply using `echo` instead of `echo2stderr` in `usage()` solves the issue, any ideas why?

**Comment by Razerban** [comment]
> Nice! That is some fancy stuff right here!
> 
> So I am getting this error when I run `./keyboard_creator.sh -p test -s MX_soldermask` :
> 
> image
> 
> And when I go to the KiCAD footprint and symbol librarires tables, `fp-lib-table` and `sym-lib-table` respectively, the libraries were not added at all!
> 
> image
> 
> image
> 
> So when I remove the two ticks from the `sed` command it works perfectly here (I'm running Arch) . Can you please check if this works on your systems?

Thank you for taking the time and test it :)

My bad, I must've changed something before committing the changes. I'll correct this.

**Comment by Razerban** [comment]
> There is also an issue with the usage function (`-h` option):
> 
> image
> 
> For some reason the linebreaks are not being processed in `echo2stderr` . I tried adding the `-e` option to the function's definition but to no avail; simply using `echo` instead of `echo2stderr` in `usage()` solves the issue, any ideas why?

I think I know

> There is also an issue with the usage function (`-h` option):
> 
> image
> 
> For some reason the linebreaks are not being processed in `echo2stderr` . I tried adding the `-e` option to the function's definition but to no avail; simply using `echo` instead of `echo2stderr` in `usage()` solves the issue, any ideas why?

I think I know what causes the text to be printed without line breaks or tabs. I'll fix it as well.

**Comment by Razerban** [comment]
> There is also an issue with the usage function (`-h` option):
> 
> image
> 
> For some reason the linebreaks are not being processed in `echo2stderr` . I tried adding the `-e` option to the function's definition but to no avail; simply using `echo` instead of `echo2stderr` in `usage()` solves the issue, any ideas why?

I think I know what causes the text to be printed without line breaks and tabs.
Look at it this way:

```bash
TEXT="line-1
line-2
line3"

echo ${TEXT}
````
this will be executed as:
```bash
echo line-1 \
line-2 \
line-3
````
i.e. `echo` with three parameters -> printing each parameter separately with a space in between them.

If we add quotes around `${TEXT}`
```bash
echo "${TEXT}"
```
the resulting command will be:
```bash
echo "line-1
line-2
line-3"
```
i.e. `echo` with a single string parameter which has three lines of text and two line breaks.

Also, I need to account for the occasional flags that get passed to the `echo` command: e.g `-e`, `-n`, ...

**Comment by Gondolindrim** [comment]
Nice! Works wonderfully now. Can you confirm this works in mac and Linux?

Also I will submit a suggestion to align the `-v, --verbose` option in `-h` since it's misaliged:

image

**Pull request merged**
